<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 =>
  array (
    'acceptable_sugar_versions' =>
    array (
      0 => '',
    ),
  ),
  1 =>
  array (
    'acceptable_sugar_flavors' =>
    array (
      0 => 'CE',
    ),
  ),
  'readme' => '',
  'key' => 'UN',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'GoldMining',
  'published_date' => '2024-07-20 14:26:19',
  'type' => 'module',
  'version' => 'v0.1',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'GoldMining',
  'beans' =>
  array (
    0 =>
    array (
      'module' => 'UN_Mining',
      'class' => 'UN_Mining',
      'path' => 'modules/UN_Mining/UN_Mining.php',
      'tab' => true,
    ),
    1 =>
    array (
      'module' => 'UN_Country',
      'class' => 'UN_Country',
      'path' => 'modules/UN_Country/UN_Country.php',
      'tab' => true,
    ),
    2 =>
    array (
      'module' => 'UN_Company',
      'class' => 'UN_Company',
      'path' => 'modules/UN_Company/UN_Company.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' =>
  array (
  ),
  'relationships' =>
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' =>
  array (
    0 =>
    array (
      'from' => '<basepath>/SugarModules/modules/UN_Mining',
      'to' => 'modules/UN_Mining',
    ),
    1 =>
    array (
      'from' => '<basepath>/SugarModules/modules/UN_Country',
      'to' => 'modules/UN_Country',
    ),
    2 =>
    array (
      'from' => '<basepath>/SugarModules/modules/UN_Company',
      'to' => 'modules/UN_Company',
    ),
    3 =>
    array (
      'from' => '<basepath>/SugarModules/custom',
      'to' => 'custom',
    ),
  ),
  'language' =>
  array (
    0 =>
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);
